### ISSUE TITLE
Add error check on event entry types [message/gameevents.c::read_game_event_definition]

### ISSUE THREAD

**Issue by Square789** [Square789/tf2_dem_py#7]
Malformed data / anything above 7 will probably cause infinite loops and other horrible malfunctions.

**Comment by alessbaas** [comment]
Hey Bro

**Comment by Square789** [comment]
Yo aless
I noticed the entry types can not be more than 7 since they're only made up of 3 bit so uuuuh yeah
Epic fail !, one could argue

**Comment by alessbaas** [comment]
Glad Yu found the problem! I, however, must humbly refute your statement, since after careful and elongated research I clearly can confirm it was not an epic fail. Happens to the best of us.
